spring.application.name=shorturl
server.port=8020


spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.auto-commit=false


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.initialization-fail-timeout=1

# === Reverse Proxy / IP forwarding ===
server.tomcat.remoteip.remote-ip-header=X-Forwarded-For
server.tomcat.remoteip.protocol-header=X-Forwarded-Proto
server.tomcat.remoteip.host-header=X-Forwarded-Host
server.tomcat.remoteip.port-header=X-Forwarded-Port
server.tomcat.remoteip.internal-proxies=.*




spring.thymeleaf.cache=false


app.admin.username=surl
app.admin.password=surl123


app.base-url=


app.log.geolocation-enabled=true

server.forward-headers-strategy=native


spring.servlet.multipart.max-file-size=50MB

spring.servlet.multipart.max-request-size=110MB

sarinah.rssapp.feed-url=https://rss.app/feeds/v1.1/ag13Zgy3l09ricDp.json


ldap.url=ldap://10.0.7.12:389
ldap.domain=sarinah.net
ldap.base-dn=DC=sarinah,DC=net

# disable manager bind
ldap.manager-dn=
ldap.manager-password=


# ldap.user-search-filter=(&(objectClass=user)(sAMAccountName={0}))
# ldap.user-search-base=DC=sarinah,DC=net

# ldap.group-search-base=OU=Groups,DC=sarinah,DC=net
# ldap.group-search-filter=(&(objectClass=group)(member={0}))

logging.level.org.springframework.security.ldap=DEBUG
logging.level.org.springframework.security.ldap.authentication.ad=DEBUG
logging.level.org.springframework.security.web.csrf=DEBUG
logging.level.org.springframework.security.web.access=DEBUG
logging.level.org.springframework.security.web.authentication=DEBUG

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.display-request-duration=true